example_regex: Main Class Reference
Main Class Reference
Static Public Member Functions
static boolean match (String input, Pattern regex)
static List< Map.Entry< String, Pattern > > makePatterns (String syntax)
static void main (String[] args)
Static Private Member Functions
static void testMatches (String[] tests, List< Map.Entry< String, Pattern >> patterns)
Detailed Description
Definition at line 10 of file Main.java.
Member Function Documentation
static void Main.main (String[] args) static
Definition at line 50 of file Main.java.
References makePatterns(), and testMatches().
static List<Map.Entry<String, Pattern> > Main.makePatterns (String syntax) static
Definition at line 35 of file Main.java.
Referenced by main().
static boolean Main.match (String input, Pattern regex) static
Definition at line 11 of file Main.java.
Referenced by testMatches().
static void Main.testMatches (String[] tests, List< Map.Entry< String, Pattern >> patterns) static private
Definition at line 18 of file Main.java.
References match().
Referenced by main().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_regex/repository/src/Main.java